SUBJECT: mailto:confamgroup@gmail.com
VAPID_PUBLIC_KEY: BOJr2z7vg9GFo8xRogByRiJGKOsnSzAGC-mJGXBDm0LWxhFamHTJqQMpxUGdo_407Wer4U40nUFe-sAh0u9E0XM=

VAPID_PRIVATE_KEY: dBdbpajwmoTdHGZepEsCj-5Ofbmra_qLRxFYA9I7EiY=
