# SUBJECT: mailto:confamgroup@gmail.com
# VAPID_PUBLIC_KEY: BESQa79iV_l8VChuRQbS8iPFAG_WFuGK_JxmXWm3wFmMAlj3Z2zRzEYdCTjg80JgRbhoAK-G7SR37eni4XQnZKc=
# VAPID_PRIVATE_KEY: W6XtR4XAWGqvT2WtSlWpDm3ZrwXmk4sx6MjHoFjO_sc=exit
